import jsPDF from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import type { AuditLog, Submission } from '../types';
import { downloadBlob, downloadTextFile } from './download';
import type { AnalyticsMetrics } from './analytics';
import { formatDateRange, type DateRange } from './date-ranges';

type AutoTableDocument = jsPDF & { lastAutoTable?: { finalY: number } };


export interface ExportReportOptions {
  includeMetrics: boolean;
  includeStatus: boolean;
  includePriority: boolean;
  includeCategory: boolean;
  includeTeamPerformance: boolean;
  includeTrends: boolean;
}

const DEFAULT_REPORT_OPTIONS: ExportReportOptions = {
  includeMetrics: true,
  includeStatus: true,
  includePriority: true,
  includeCategory: true,
  includeTeamPerformance: true,
  includeTrends: true,
};

function humanizeKey(key: string): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function formatAuditDetailValue(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (Array.isArray(value)) return value.map(formatAuditDetailValue).filter(Boolean).join(', ');
  if (value instanceof Date) return value.toLocaleString();
  if (typeof value === 'object') {
    if ('toDate' in value && typeof (value as { toDate?: unknown }).toDate === 'function') {
      return ((value as { toDate: () => Date }).toDate()).toLocaleString();
    }
    return Object.entries(value as Record<string, unknown>)
      .map(([key, nestedValue]) => `${humanizeKey(key)}: ${formatAuditDetailValue(nestedValue)}`)
      .join('; ');
  }
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

export function formatAuditDetails(details: AuditLog['details']): string {
  if (!details || Object.keys(details).length === 0) return '—';
  return Object.entries(details)
    .map(([key, value]) => `${humanizeKey(key)}: ${formatAuditDetailValue(value) || '—'}`)
    .join('; ');
}

function getLastTableY(doc: jsPDF, fallback: number): number {
  return (doc as AutoTableDocument).lastAutoTable?.finalY ?? fallback;
}


// Brand colors (RGB)
const BRAND_PRIMARY_RGB: [number, number, number] = [46, 134, 171];
const BRAND_SECONDARY_RGB: [number, number, number] = [30, 58, 95];
const BRAND_ACCENT_RGB: [number, number, number] = [235, 245, 251];
const TEXT_MUTED_RGB: [number, number, number] = [107, 123, 141];

function addBrandedHeader(doc: jsPDF, pageWidth: number): number {
  // Gradient-style header bar (solid primary, then secondary label)
  doc.setFillColor(...BRAND_SECONDARY_RGB);
  doc.rect(0, 0, pageWidth, 22, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('FeedSolve', 14, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(180, 210, 230);
  doc.text('Collect. Resolve. Grow.', pageWidth - 14, 14, { align: 'right' });

  doc.setTextColor(30, 58, 95);
  return 28;
}

function addPageNumbers(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED_RGB);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' }
    );
    doc.text('feedsolve.com', pageWidth - 14, pageHeight - 8, { align: 'right' });
  }
}

function addBrandedFooterNote(doc: jsPDF, yPos: number, pageWidth: number, margin: number): void {
  doc.setFillColor(...BRAND_ACCENT_RGB);
  doc.roundedRect(margin, yPos, pageWidth - margin * 2, 16, 2, 2, 'F');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED_RGB);
  doc.text(
    'Generated by FeedSolve · Collect feedback. Resolve it fast. · feedsolve.com',
    pageWidth / 2,
    yPos + 10,
    { align: 'center' }
  );
}

export async function exportPDFReport(
  metrics: AnalyticsMetrics,
  dateRange: DateRange,
  companyName: string,
  reportOptions: ExportReportOptions = DEFAULT_REPORT_OPTIONS
): Promise<Blob> {
  const options = { ...DEFAULT_REPORT_OPTIONS, ...reportOptions };
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;

  let yPosition = addBrandedHeader(doc, pageWidth);

  // Report title block
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...BRAND_SECONDARY_RGB);
  doc.text('Analytics Report', margin, yPosition);
  yPosition += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED_RGB);
  doc.text(`Company: ${companyName}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Period: ${formatDateRange(dateRange)}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
  yPosition += 3;

  // Divider line
  doc.setDrawColor(...BRAND_PRIMARY_RGB);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  doc.setTextColor(30, 58, 95);

  const ensureSpace = (needed = 50) => {
    if (yPosition > pageHeight - needed - 20) {
      doc.addPage();
      yPosition = addBrandedHeader(doc, pageWidth);
      yPosition += 4;
    }
  };

  let sectionAdded = false;

  if (options.includeMetrics) {
    ensureSpace();
    addSectionTitle(doc, 'Key Metrics', margin, yPosition);
    yPosition += 8;

    const metricsData = [
      ['Metric', 'Value'],
      ['Total Submissions', metrics.totalSubmissions.toString()],
      ['Resolved Submissions', metrics.resolvedSubmissions.toString()],
      ['Resolution Rate', `${metrics.resolutionRate.toFixed(1)}%`],
      ['Avg Resolution Time', `${metrics.averageResolutionTime.toFixed(1)} days`],
    ];

    autoTable(doc, {
      startY: yPosition,
      head: metricsData.slice(0, 1),
      body: metricsData.slice(1),
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      theme: 'grid',
      headStyles: { fillColor: BRAND_SECONDARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 251] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    yPosition = getLastTableY(doc, yPosition) + 12;
    sectionAdded = true;
  }

  if (options.includeStatus) {
    ensureSpace();
    addSectionTitle(doc, 'Submissions by Status', margin, yPosition);
    yPosition += 8;

    const statusData = [
      ['Status', 'Count'],
      ...Object.entries(metrics.submissionsByStatus).map(([status, count]) => [
        status.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
        count.toString(),
      ]),
    ];

    autoTable(doc, {
      startY: yPosition,
      head: statusData.slice(0, 1),
      body: statusData.slice(1),
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      theme: 'grid',
      headStyles: { fillColor: BRAND_PRIMARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 251] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    yPosition = getLastTableY(doc, yPosition) + 12;
    sectionAdded = true;
  }

  if (options.includePriority) {
    ensureSpace();
    addSectionTitle(doc, 'Submissions by Priority', margin, yPosition);
    yPosition += 8;

    const priorityData = [
      ['Priority', 'Count'],
      ...Object.entries(metrics.submissionsByPriority).map(([priority, count]) => [
        priority.charAt(0).toUpperCase() + priority.slice(1),
        count.toString(),
      ]),
    ];

    autoTable(doc, {
      startY: yPosition,
      head: priorityData.slice(0, 1),
      body: priorityData.slice(1),
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      theme: 'grid',
      headStyles: { fillColor: BRAND_PRIMARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 251] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    yPosition = getLastTableY(doc, yPosition) + 12;
    sectionAdded = true;
  }

  if (options.includeCategory && Object.keys(metrics.submissionsByCategory).length > 0) {
    ensureSpace();
    addSectionTitle(doc, 'Submissions by Category', margin, yPosition);
    yPosition += 8;

    const categoryData = [
      ['Category', 'Count'],
      ...Object.entries(metrics.submissionsByCategory).map(([category, count]) => [
        category,
        count.toString(),
      ]),
    ];

    autoTable(doc, {
      startY: yPosition,
      head: categoryData.slice(0, 1),
      body: categoryData.slice(1),
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      theme: 'grid',
      headStyles: { fillColor: BRAND_PRIMARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 251] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    yPosition = getLastTableY(doc, yPosition) + 12;
    sectionAdded = true;
  }

  if (options.includeTrends && metrics.trendData.length > 0) {
    ensureSpace();
    addSectionTitle(doc, 'Trend Analysis', margin, yPosition);
    yPosition += 8;

    const trendData = [
      ['Date', 'Submissions', 'Resolved'],
      ...metrics.trendData.map((point) => [
        point.date,
        point.count.toString(),
        point.resolved.toString(),
      ]),
    ];

    autoTable(doc, {
      startY: yPosition,
      head: trendData.slice(0, 1),
      body: trendData.slice(1),
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      theme: 'grid',
      headStyles: { fillColor: BRAND_SECONDARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 251] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    yPosition = getLastTableY(doc, yPosition) + 12;
    sectionAdded = true;
  }

  if (options.includeTeamPerformance && metrics.teamPerformance.length > 0) {
    ensureSpace(70);
    addSectionTitle(doc, 'Team Performance', margin, yPosition);
    yPosition += 8;

    const teamData = [
      ['Team Member', 'Assigned', 'Resolved', 'Resolution Rate', 'Avg Time (days)'],
      ...metrics.teamPerformance.map((member) => [
        member.userName || member.userEmail,
        member.assignedCount.toString(),
        member.resolvedCount.toString(),
        `${member.resolutionRate.toFixed(1)}%`,
        member.averageResolutionTime.toFixed(1),
      ]),
    ];

    autoTable(doc, {
      startY: yPosition,
      head: teamData.slice(0, 1),
      body: teamData.slice(1),
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      theme: 'grid',
      headStyles: { fillColor: BRAND_SECONDARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 251] },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 55 },
        1: { cellWidth: 25 },
        2: { cellWidth: 25 },
        3: { cellWidth: 38 },
        4: { cellWidth: 38 },
      },
    });

    yPosition = getLastTableY(doc, yPosition) + 12;
    sectionAdded = true;
  }

  if (!sectionAdded) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_MUTED_RGB);
    doc.text('No report sections were selected.', margin, yPosition);
    yPosition += 10;
  }

  // Branded footer note on last page
  ensureSpace(26);
  addBrandedFooterNote(doc, yPosition, pageWidth, margin);

  // Page numbers on all pages
  addPageNumbers(doc);

  const pdfBlob = doc.output('blob');
  return pdfBlob;
}

export async function downloadPDFReport(
  metrics: AnalyticsMetrics,
  dateRange: DateRange,
  companyName: string,
  options?: ExportReportOptions,
  filenamePrefix = 'analytics-report'
): Promise<void> {
  const blob = await exportPDFReport(metrics, dateRange, companyName, options);
  const now = new Date();
  const datePart = now.toISOString().split('T')[0];
  const timePart = `${now.getHours().toString().padStart(2, '0')}${now.getMinutes().toString().padStart(2, '0')}${now.getSeconds().toString().padStart(2, '0')}`;
  downloadBlob(blob, `${filenamePrefix}-${datePart}-${timePart}.pdf`);
}

export function exportCSVSubmissions(submissions: Submission[]): string {
  const headers = [
    'Tracking Code',
    'Subject',
    'Category',
    'Status',
    'Priority',
    'Assigned To',
    'Created At',
    'Resolved At',
    'Resolution Time (days)',
  ];

  const rows = submissions.map((sub) => {
    const createdDate = sub.createdAt instanceof Date ? sub.createdAt : sub.createdAt?.toDate();
    const resolvedDate = sub.resolvedAt instanceof Date ? sub.resolvedAt : sub.resolvedAt?.toDate();

    let resolutionTime = '';
    if (createdDate && resolvedDate) {
      resolutionTime = Math.floor(
        (resolvedDate.getTime() - createdDate.getTime()) / (1000 * 60 * 60 * 24)
      ).toString();
    }

    return [
      sub.trackingCode,
      `"${sub.subject.replace(/"/g, '""')}"`,
      sub.category,
      sub.status,
      sub.priority,
      sub.assignedTo || 'Unassigned',
      createdDate?.toISOString() || '',
      resolvedDate?.toISOString() || '',
      resolutionTime,
    ];
  });

  const csv = [headers, ...rows].map((row) => row.join(',')).join('\n');
  return csv;
}

export function downloadCSV(submissions: Submission[]): void {
  const csv = exportCSVSubmissions(submissions);
  downloadTextFile(csv, `submissions-${new Date().toISOString().split('T')[0]}.csv`, 'text/csv;charset=utf-8;');
}

function formatAuditDate(value: AuditLog['createdAt']): string {
  if (!value) return '—';
  if (value instanceof Date) return value.toLocaleString();
  return value.toDate().toLocaleString();
}

export function exportAuditLogsPDF(logs: AuditLog[], companyName: string): Blob {
  const doc = new jsPDF({ orientation: 'landscape' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Branded header bar
  doc.setFillColor(...BRAND_SECONDARY_RGB);
  doc.rect(0, 0, pageWidth, 18, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text('FeedSolve', margin, 12);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(180, 210, 230);
  doc.text('Collect. Resolve. Grow.', pageWidth - margin, 12, { align: 'right' });

  doc.setTextColor(...BRAND_SECONDARY_RGB);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Audit Logs Report', margin, 30);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED_RGB);
  doc.text(`Company: ${companyName}`, margin, 38);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 44);
  doc.text(`Total Records: ${logs.length}`, margin, 50);

  autoTable(doc, {
    startY: 56,
    head: [['Timestamp', 'User', 'Action', 'Resource Type', 'Resource', 'Details']],
    body: logs.map((log) => [
      formatAuditDate(log.createdAt),
      `${log.userName || 'Unknown'}\n${log.userEmail || ''}`,
      log.action,
      log.resourceType.replace(/_/g, ' '),
      log.resourceName ?? log.resourceId ?? '',
      formatAuditDetails(log.details),
    ]),
    margin: { left: margin, right: margin },
    theme: 'grid',
    headStyles: { fillColor: BRAND_SECONDARY_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 248, 251] },
    styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 34 },
      1: { cellWidth: 48 },
      2: { cellWidth: 42 },
      3: { cellWidth: 30 },
      4: { cellWidth: 46 },
      5: { cellWidth: 68 },
    },
  });

  // Page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const ph = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...TEXT_MUTED_RGB);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, ph - 6, { align: 'center' });
    doc.text('feedsolve.com', pageWidth - margin, ph - 6, { align: 'right' });
  }

  return doc.output('blob');
}

export function downloadAuditLogsPDF(logs: AuditLog[], companyName: string): void {
  const blob = exportAuditLogsPDF(logs, companyName);
  downloadBlob(blob, `audit-logs-${new Date().toISOString().split('T')[0]}.pdf`);
}

function addSectionTitle(doc: jsPDF, title: string, x: number, y: number): void {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_SECONDARY_RGB);
  doc.text(title, x, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(30, 58, 95);
}
